######################################################################
##
## Filename: BCD_check_register.udo
## Created on: Fri Jun 08 14:37:47 Mitteleuropäische Sommerzeit 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
