######################################################################
##
## Filename: BCD_check_simple.udo
## Created on: Fri Jun 08 13:38:57 Mitteleuropäische Sommerzeit 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
