######################################################################
##
## Filename: Ripple_Carry_4b.udo
## Created on: Fri May 25 14:49:24 Mitteleuropäische Sommerzeit 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
